language: python
allow_failures:
  - python: "3.4_with_system_site_packages"
python:
  - "2.7_with_system_site_packages"
# don't work
#  - "3.4_with_system_site_packages"
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - pip install sklearn
  - pip install pandas
script:
  - cd stacked_generalization/lib/test
  - python test.py
  - cd ../../example
  - python cross_validation_for_iris.py
  - python simple_regression.py
  - python joblibed_classification.py
  - python fwls_regression.py
