language: python
python:
  - "2.7_with_system_site_packages"
before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-sklearn
script:
  - python stacked_generalization/lib/test/test.py
  - python stacked_generalization/example/cross_validation_for_iris.py
  - python stacked_generalization/example/simple_regression.py
